# Generated by Django 5.0.4 on 2026-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
    ]
