# Generated by Django 5.0.4 on 2026-04-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_borrowrecord_earned_points_visit_earned_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('desc', models.CharField(max_length=200)),
                ('criteria_type', models.CharField(choices=[('visits_week', 'Visits in last 7 days'), ('visits_month_top10', 'Top 10 Visits this month'), ('borrows_semester', 'Borrows in last 6 months'), ('custom', 'Custom / Manual')], max_length=50)),
                ('min_value', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LevelTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_num', models.IntegerField(unique=True)),
                ('min_xp', models.IntegerField()),
                ('max_xp', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#95a5a6', max_length=7)),
            ],
            options={
                'ordering': ['min_xp'],
            },
        ),
        migrations.CreateModel(
            name='PointPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('visit', 'Visit'), ('borrow', 'Borrow Book')], max_length=50, unique=True)),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Point Policies',
            },
        ),
    ]
