# Generated by Django 5.0.4 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_badgerule_leveltier_pointpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpolicy',
            name='action_type',
            field=models.CharField(help_text='Contoh: visit, borrow, return_on_time, review_book', max_length=50, unique=True),
        ),
    ]
