# Generated by Django 5.0.4 on 2026-04-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(db_index=True, max_length=50)),
                ('amount', models.IntegerField(help_text='Format: + for event, - for redemption')),
                ('transaction_type', models.CharField(choices=[('event', 'Event Participation'), ('redeem', 'Redeem Reward'), ('manual', 'Manual Adjustment')], default='manual', max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('points_cost', models.IntegerField(default=100)),
                ('stock', models.IntegerField(default=10)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=50)),
                ('points_used', models.IntegerField()),
                ('redeem_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval / Claim'), ('claimed', 'Claimed'), ('rejected', 'Rejected / Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
