# Generated by Django 5.0.4 on 2026-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_pointtransaction_reward_redemption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redemption',
        ),
    ]
