# Generated by Django 5.0.4 on 2026-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_delete_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama atau Judul Seminar', max_length=200)),
                ('csv_file', models.FileField(help_text='Upload file CSV berisi satu kolom NIM/Cardnumber', upload_to='seminars/')),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload CSV Seminar',
                'verbose_name_plural': 'Upload CSV Seminar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('event', 'Event Participation'), ('seminar', 'Seminar Attendance'), ('redeem', 'Redeem Reward'), ('manual', 'Manual Adjustment')], default='manual', max_length=20),
        ),
    ]
