# Generated by Django 5.0.4 on 2026-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_seminarupload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Input Data Seminar', 'verbose_name_plural': 'Input Data Seminar'},
        ),
        migrations.AddField(
            model_name='seminarupload',
            name='manual_input',
            field=models.TextField(blank=True, help_text='Atau input NIM/Cardnumber mahasiswa di sini (satu NIM per baris)'),
        ),
        migrations.AlterField(
            model_name='seminarupload',
            name='csv_file',
            field=models.FileField(blank=True, help_text='Upload file CSV berisi satu kolom NIM/Cardnumber', null=True, upload_to='seminars/'),
        ),
    ]
