# Generated by Django 5.0.4 on 2026-06-03 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending / Belum Diambil'), ('claimed', 'Claimed / Sudah Diambil')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='leaderboard.member')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='leaderboard.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
