# Generated by Django 5.0.4 on 2026-06-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_redemptionclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul Seminar', max_length=200)),
                ('speaker', models.CharField(help_text='Pembicara/Narasumber', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Deskripsi Singkat Seminar', null=True)),
                ('date', models.DateTimeField(help_text='Tanggal & Waktu Seminar')),
                ('registration_open', models.DateTimeField(help_text='Tanggal Dibuka Pendaftaran')),
                ('registration_close', models.DateTimeField(help_text='Tanggal Ditutup Pendaftaran')),
                ('points_register', models.IntegerField(default=2, help_text='Poin untuk mendaftar')),
                ('points_attend', models.IntegerField(default=15, help_text='Poin untuk kehadiran')),
                ('claim_code', models.CharField(help_text='Kode Unik Klaim Kehadiran (misal: UMS-SEM-XYZ)', max_length=50, unique=True)),
                ('claim_code_active', models.BooleanField(default=False, help_text='Apakah klaim kehadiran sedang aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, help_text='NIM / Cardnumber', max_length=50)),
                ('email', models.EmailField(help_text='Email Mahasiswa saat mendaftar', max_length=254)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Terdaftar'), ('attended', 'Hadir / Diklaim')], default='registered', max_length=20)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='leaderboard.seminar')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('seminar', 'member_id')},
            },
        ),
    ]
