# Generated by Django 5.0.4 on 2026-06-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0013_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reset_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (Reset Kapan Saja)"),
                            ("auto_semester", "Otomatis Tiap Semester (Jan & Jul)"),
                            ("auto_yearly", "Otomatis Tahunan"),
                        ],
                        default="auto_semester",
                        help_text="Pilih sistem kapan poin & klasemen akan di-reset menjadi 0.",
                        max_length=20,
                    ),
                ),
                (
                    "yearly_reset_month",
                    models.IntegerField(
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ],
                        default=8,
                        help_text="Jika memilih 'Otomatis Tahunan', pada tanggal 1 bulan apa reset dilakukan? (Default: Agustus)",
                    ),
                ),
                (
                    "manual_reset_date",
                    models.DateField(
                        blank=True,
                        help_text="Jika memilih 'Manual', masukkan tanggal mulainya musim ini. Semua poin sebelum tanggal ini akan diabaikan.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Reset Poin",
                "verbose_name_plural": "Pengaturan Reset Poin",
            },
        ),
    ]
