# Generated by Django 5.0.4 on 2026-06-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0014_leaderboardconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reward",
            name="image_url",
        ),
        migrations.AddField(
            model_name="reward",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar akan otomatis dikompres menjadi PNG maksimal 500px.",
                null=True,
                upload_to="rewards/",
            ),
        ),
    ]
