# Generated by Django 5.0.4 on 2026-06-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0015_remove_reward_image_url_reward_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="seminarupload",
            name="points",
            field=models.IntegerField(
                default=15,
                help_text="Jumlah poin yang akan diberikan ke setiap mahasiswa",
            ),
        ),
    ]
