# Generated by Django 5.0.4 on 2026-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0016_seminarupload_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redemptionclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending / Belum Diambil"),
                    ("claimed", "Claimed / Sudah Diambil"),
                    ("rejected", "Rejected / Ditolak"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
