# Generated by Django 5.0.4 on 2026-09-08 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0017_alter_redemptionclaim_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Upload Kehadiran (CSV)', 'verbose_name_plural': 'Upload Kehadiran (CSV)'},
        ),
        migrations.AddField(
            model_name='seminarupload',
            name='seminar',
            field=models.ForeignKey(blank=True, help_text='Pilih Event / Seminar yang diselenggarakan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='leaderboard.seminar'),
        ),
        migrations.AlterField(
            model_name='seminarupload',
            name='points',
            field=models.IntegerField(blank=True, help_text='Opsional: Poin per peserta (jika dikosongkan, otomatis mengambil dari Kebijakan Poin XP / Event)', null=True),
        ),
        migrations.AlterField(
            model_name='seminarupload',
            name='title',
            field=models.CharField(blank=True, help_text='Opsional: Judul/Catatan tambahan', max_length=200),
        ),
    ]
