# Generated by Django 5.0.4 on 2026-09-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0018_alter_seminarupload_options_seminarupload_seminar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, help_text='Poster / Banner Seminar (Disarankan aspek rasio 16:9 atau 4:3, resolusi ideal 1200x675px, format JPG/PNG/WebP)', null=True, upload_to='seminars/'),
        ),
    ]
