# Generated by Django 5.0.4 on 2026-09-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0019_seminar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='cert_font_family',
            field=models.CharField(choices=[('arialbd.ttf', 'Arial Bold'), ('arial.ttf', 'Arial Regular'), ('timesbd.ttf', 'Times New Roman Bold'), ('times.ttf', 'Times New Roman Regular'), ('calibrib.ttf', 'Calibri Bold'), ('calibri.ttf', 'Calibri Regular')], default='arialbd.ttf', help_text='Pilihan Font untuk Nama Peserta', max_length=50),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_name_color',
            field=models.CharField(default='#1e293b', help_text='Warna teks Nama Peserta (Hex: misal #000000 atau #1e293b)', max_length=20),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_name_font_size',
            field=models.IntegerField(default=52, help_text='Ukuran Font Nama Peserta (pt/px)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_name_pos_y',
            field=models.IntegerField(default=560, help_text='Posisi vertikal Y untuk Nama Peserta (dalam pixel)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_nim_pos_y',
            field=models.IntegerField(default=630, help_text='Posisi vertikal Y untuk NIM Peserta (dalam pixel)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_number_pos_y',
            field=models.IntegerField(default=320, help_text='Posisi vertikal Y untuk Nomor Sertifikat (dalam pixel)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_number_template',
            field=models.CharField(blank=True, help_text='Format Nomor Sertifikat (Contoh: UMS/LIB-SEM/2026/{num:03d} atau nomor statis panitia)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_show_nim',
            field=models.BooleanField(default=True, help_text='Tampilkan teks NIM di bawah nama peserta'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='cert_template',
            field=models.ImageField(blank=True, help_text='Template Desain Sertifikat Kosong (Format PNG/JPG/WebP, disarankan A4 Landscape resolusi 1920x1080 atau lebih besar)', null=True, upload_to='cert_templates/'),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Nomor Sertifikat Peserta', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='seminarregistration',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='File PDF E-Sertifikat Peserta', null=True, upload_to='certificates/'),
        ),
    ]
