# Generated by Django 5.0.4 on 2026-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0020_seminar_cert_font_family_seminar_cert_name_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='category',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('training', 'Pelatihan / Training'), ('webinar', 'Webinar / Zoom'), ('book_review', 'Bedah Buku'), ('other', 'Lainnya')], default='seminar', help_text='Kategori Acara (Seminar, Workshop, Pelatihan, Webinar/Zoom, Bedah Buku, dll)', max_length=50),
        ),
        migrations.AddField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, default='Ruang Seminar Perpustakaan UMS', help_text='Lokasi Acara (misal: Ruang Seminar Lt. 2 UMS atau Online via Zoom)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Link Ruang Virtual (Zoom / Google Meet / Teams) jika acara diselenggarakan daring', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateTimeField(help_text='Tanggal & Waktu Acara'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, help_text='Deskripsi Singkat Acara', null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, help_text='Poster / Banner Acara (Disarankan aspek rasio 16:9 atau 4:3, resolusi ideal 1200x675px, format JPG/PNG/WebP)', null=True, upload_to='seminars/'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.CharField(help_text='Pembicara / Narasumber / Trainer', max_length=100),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(help_text='Judul Acara / Seminar', max_length=200),
        ),
    ]
