# Generated by Django 5.0.4 on 2026-09-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_seminar_category_seminar_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='event_mode',
            field=models.CharField(choices=[('offline', 'Tatap Muka (Offline)'), ('online', 'Daring (Online / Zoom)'), ('hybrid', 'Hybrid (Offline & Online)')], default='offline', help_text='Metode Pelaksanaan: Tatap Muka (Offline), Daring (Online / Zoom), atau Hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, default='Ruang Seminar Perpustakaan UMS', help_text='Lokasi Acara Fisik (misal: Ruang Seminar Lt. 2 Perpustakaan UMS)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='meeting_url',
            field=models.URLField(blank=True, help_text='Link Ruang Virtual (Zoom / Google Meet / Teams) jika acara diselenggarakan daring / hybrid', max_length=500, null=True),
        ),
    ]
